### PR TITLE
Shift in the way the Robot main class works

### PR DESCRIPTION
**Pull request by tandej**
Moves from just having a xyzPeriodic() and xyzInit() method for every possible robot state, to just having unified methods for each, passing in the robot state. (This is a class that users will override, and does not work with the WPILib templates. Might like making our own templates in the future.)

Tagging Floyd on this because it's the kind of change that he might like knowing about.

### CODE REVIEW

**Comment by tandej** [comment]
Retracting to draft so I can add a couple features.

**Review by elliotnash — APPROVED** [review]

**Comment by elliotnash** [comment]
I know I just approved this but maybe naming something other than SRobot? Your choice

**Comment by elliotnash** [comment]
Should this still be a draft?

**Comment by tandej** [comment]
It's ready. Verified to be 100% functional in simulation.

**Pull request merged**
